<Project>
  <PropertyGroup>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' != ''">true</ContinuousIntegrationBuild>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'Qserve.UI'">
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup Condition="'$(MSBuildProjectName)' == 'Qserve.UI'">
    <Page Include="Localization\*.xaml" />
    <Page Include="Themes\*.xaml" />
    <Page Include="Styles\*.xaml" />
    <Page Include="Views\*.xaml" />
  </ItemGroup>
</Project>
